apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
        - name: fibonacci-server
          image: registry.dev.svc.cluster.local:5000/fibonacci-server:latest # this is a trick from my hosts file it needs to replaced in another env
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
      #imagePullSecrets:
      #  - name: my-registry-secret
