apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
        - name: fibonacci-server
          image: fibonacci-server-1.0.0
          ports:
            - containerPort: 9000
