apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonacci-server
  template:
    metadata:
      labels:
        app: fibonacci-server
    spec:
      containers:
        - name: fibonacci-server
          image: http://192.168.1.106:5000/fibonacci-server:latest # this is my ip host it needs to replaced in another env
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /health
              port: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-server
spec:
  selector:
    app: fibonacci-server
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9000
  type: LoadBalancer
